//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tbl_historialmedico
{
    public int id { get; set; }
    public string id_usuario { get; set; }
    public string nombre { get; set; }
    public string doctor { get; set; }
    public string descripcion { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
}
